server:
  port: 9999

key:
  private.file: config/private.pem
  public.file: config/public.pem

eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

security:
  oauth2:
    authorization.token-key-access: "permitAll()"