server.port: 7070
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: new-photo
          group: image-scaler
          content-type: application/json
      rabbit:
        bindings:
          input:
            consumer.durable-subscription: true
eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
