server.port: 8761
eureka:
  instance.hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url.default_zone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
  server:
    response-cache-update-interval-ms: 500
    eviction-interval-timer-in-ms: 500
logging:
  level:
    com.netflix.eureka.registry.AbstractInstanceRegistry: WARN